ports:
  - port: 8081
    onOpen: ignore
    visibility: public
  - port: 19000
    onOpen: ignore
    visibility: public
  - port: 19001
    onOpen: ignore
    visibility: public
  - port: 19002
    onOpen: ignore
    visibility: public

tasks:
  - init: npm install
    command: npm start 